### PR TITLE
Restructure solution for a new baseline

### PR DESCRIPTION
**Pull request by chrisriesgo**
Pending formal discussion:

- Restructured the solution
- Moved the old `TrueMyth.csproj` into a *samples* folder. Renamed to `TrueMythConsole`
- Created a new `TrueMyth.csproj` .NET Standard 1.0 library to house `Maybe` and `Result`
- Added a few mostly-empty README files to be filled in later
-------------------------------
Restructured the solution:
**From:**
- TrueMyth
    - `Maybe.cs`    
    - `TrueMyth.csproj`

**To:**
- samples
    - TrueMythConsole
        - `Program.cs`
- src
    - TrueMyth
        - `Maybe.cs`
        - `Result.cs`
        - `TrueMyth.csproj`
- test

### CODE REVIEW

**Review by chriskrycho — APPROVED** [review]
YES PLEASE.

**Comment by chrisriesgo** [comment]
@chriskrycho I opened this quick PR to give the project a `src` + `tests` folder structure, but I imagine the existing "Program" might turn into an `example` of some kind? And we'd create a library project? Maybe we can do that later?

**Comment by chriskrycho** [comment]
Yeah, using it as an example – or, equally, just dropping it in favor of the README and docs – seems sensible to me. I only needed that particular bit specifically for the teaching aspect, as something I could walk through in real-time.

**Comment by chriskrycho** [comment]
@aggieben, since I see you also forked – if you're on the same page with @chrisriesgo here, I'll happily merge it and we can proceed with that!

**Comment by chrisriesgo** [comment]
@chriskrycho - updated the PR. made the old .csproj a baseline example/sample, then created a new csproj netstandard lib (can really be changed to whatever we want) with Maybe and Result living under it.

Unless you have some other ideas, @aggieben

**Comment by aggieben** [comment]
Looks good to me, @chriskrycho @chrisriesgo

**Comment by chriskrycho** [comment]
:shipit:

**Pull request merged**
